site_name: Martin.js
pages:
- [index.md, Home]
- [overview.md, Overview]
- [utilities.md, Utilities]
- [layers.md, Layers]
- [elements.md, Elements]
- [effects.md, Effects]
- [events.md, Events]
- [plugins.md, Plugins]
- [demos.md, Demos]
theme: readthedocs
